[versions]
conventionalCommitsPluginVersion = "3.1.3"
hoplite = "2.8.2"
koin-bom = "4.0.0"
kotlinVersion = "2.0.21"
ktorVersion = "3.0.0"
logbackVersion = "1.5.11"
mongodb-coroutines = "5.2.0"

[libraries]
hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hoplite-hocon = { module = "com.sksamuel.hoplite:hoplite-hocon", version.ref = "hoplite" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }
koin-logger = { module = "io.insert-koin:koin-logger-slf4j" }
#kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinVersion" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktorVersion" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktorVersion" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktorVersion" }
ktor-server-callLogging = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktorVersion" }
ktor-server-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktorVersion" }
ktor-server-core-jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktorVersion" }
ktor-server-defaultHeaders = { module = "io.ktor:ktor-server-default-headers-jvm", version.ref = "ktorVersion" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktorVersion" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktorVersion" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions", version.ref = "ktorVersion" }
ktor-server-tests = "io.ktor:ktor-server-tests-jvm:3.0.0-beta-2"
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktorVersion" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackVersion" }
mongodb-coroutines = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongodb-coroutines" }

[bundles]
hoplite = [
    "hoplite-core",
    "hoplite-hocon",
]
koin = [
    "koin-core",
    "koin-ktor",
    "koin-logger",
]
ktor-server = [
    "ktor-serialization-json",
    "ktor-server-auth",
    "ktor-server-auth-jwt",
    "ktor-server-callLogging",
    "ktor-server-contentNegotiation",
    "ktor-server-core-jvm",
    "ktor-server-defaultHeaders",
    "ktor-server-netty",
    "ktor-server-resources",
    "ktor-server-sessions",
    "ktor-server-websockets"
]

[plugins]
conventionalCommits = { id = "it.nicolasfarabegoli.conventional-commits", version.ref = "conventionalCommitsPluginVersion" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
ktor = { id = "io.ktor.plugin", version.ref = "ktorVersion" }
